### ISSUE TITLE
GitHub icon color

### ISSUE THREAD

**Issue by agitter** [ur-whitelab/LLMs-in-science#2]
Thanks for the incredible resource. I'll see what I can contribute to it once I review what you already have.

Having links to GitHub repositories is helpful, but it is hard to see the light GitHub icon:
![image](https://github.com/ur-whitelab/LLMs-in-science/assets/3532898/b4fc68a4-512c-4603-b3bd-31b383ebf0bc)

![image](https://github.com/ur-whitelab/LLMs-in-science/assets/3532898/6b096e3d-89a6-40e4-a0e1-713cf2a3667c)

**Comment by maykcaldas** [comment]
Oh, sorry for that. I use GH dark mode, so they looks good to me. I will change it for a version that works fine on both versions

**Comment by maykcaldas** [comment]
Thanks for bringing attention to this issue. It was fixed

**Comment by agitter** [comment]
Thanks!
